steps:
  - id: fetch-dependencies-cache
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: ['../yarn-cache-builder/yarn-cache-fetch.sh', '${_CACHE_BUCKET}']
    dir: 'frontend'
  - id: yarn-install
    name: node:12.13.1
    entrypoint: yarn
    args: ['install']
    dir: 'frontend'
  - id: yarn-build
    name: node:12.13.1
    entrypoint: yarn
    args: ['build']
    dir: 'frontend'
  - id: copy-dist
    name: gcr.io/cloud-builders/gsutil
    args: ['cp','-r','frontend/dist/frontend-app/*', '${_FRONTEND_BUCKET}']
    waitFor:
      - yarn-build
  - id: push-dependencies-cache
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: ['../yarn-cache-builder/yarn-cache-push.sh', '${_CACHE_BUCKET}']
    dir: 'frontend'
